#!/bin/bash

# Hardware setup validation script for STM32F103C8T6 Quadrature Generator

echo "STM32F103C8T6 Quadrature Generator - Hardware Setup Validation"
echo "============================================================="
echo ""

echo "📋 Pin Configuration Checklist:"
echo ""
echo "Power and Clock:"
echo "  ☐ VCC connected to 3.3V"
echo "  ☐ GND connected to ground"
echo "  ☐ External 8MHz crystal installed (or HSI will be used)"
echo ""

echo "Quadrature Outputs:"
echo "  ☐ PA8  (TIM1_CH1) - Quadrature Output A"
echo "  ☐ PA9  (TIM1_CH2) - Quadrature Output B"
echo "  ☐ PA10 (TIM2_CH3) - Quadrature Output C (90° shifted)"
echo "  ☐ PA11 (TIM2_CH4) - Quadrature Output D (90° shifted)"
echo ""

echo "User Interface:"
echo "  ☐ PA0  - Potentiometer center tap (10kΩ recommended)"
echo "  ☐ PA12 - Enable button (pulled up, active low)"
echo "  ☐ PA15 - Disable button (pulled up, active low)"
echo "  ☐ PC13 - Status LED (built-in on Blue Pill)"
echo ""

echo "Communication:"
echo "  ☐ PA2  - UART TX (115200 baud)"
echo "  ☐ PA3  - UART RX (115200 baud)"
echo ""

echo "🔧 Software Requirements:"
echo "  ☐ ARM GCC toolchain installed"
echo "  ☐ CMake version 3.20 or higher"
echo "  ☐ STM32 programming tool (st-flash, OpenOCD, etc.)"
echo ""

echo "🧪 Testing Procedure:"
echo ""
echo "1. Power on the STM32F103C8T6 board"
echo "2. Connect UART terminal at 115200 baud"
echo "3. You should see: 'STM32F103 Quadrature Generator v1.0'"
echo "4. Adjust potentiometer - frequency should change between 10Hz-1kHz"
echo "5. Press enable button - LED should turn on, outputs should start"
echo "6. Press disable button - LED should turn off, outputs should stop"
echo "7. Monitor UART for status updates every 500ms:"
echo "   Format: 'ADC: XXXX, Freq: XXXHz, Output: ON/OFF'"
echo ""

echo "📊 Expected Waveforms:"
echo ""
echo "With oscilloscope connected to PA8, PA9, PA10, PA11:"
echo "  • All outputs should be square waves with 50% duty cycle"
echo "  • PA8 and PA9 should be in phase"
echo "  • PA10 and PA11 should be 90° ahead of PA8/PA9"
echo "  • Frequency should match UART-reported frequency"
echo "  • All outputs should start/stop together when enabled/disabled"
echo ""

echo "🐛 Troubleshooting:"
echo ""
echo "No UART output:"
echo "  → Check wiring of PA2 (TX) and PA3 (RX)"
echo "  → Verify baud rate is set to 115200"
echo "  → Check power supply and reset"
echo ""
echo "No quadrature outputs:"
echo "  → Ensure enable button has been pressed"
echo "  → Check LED status on PC13"
echo "  → Verify timer pin connections (PA8-PA11)"
echo ""
echo "Incorrect frequency:"
echo "  → Check potentiometer wiring to PA0"
echo "  → Verify potentiometer is connected between VCC and GND"
echo "  → Check ADC readings in UART output"
echo ""
echo "Phase relationship incorrect:"
echo "  → This indicates timer synchronization issue"
echo "  → Check firmware configuration and rebuild"
echo ""

echo "✅ Setup validation complete!"
echo "For more details, see README.md in the project root."